### ISSUE TITLE
Getting an error : No such file or directory

### ISSUE THREAD

**Issue by shivam46** [knowledgedefinednetworking/a-deep-rl-approach-for-sdn-routing-optimization#10]
Now we build the Actor model
Now we build the Actor model
2021-02-10 15:19:50.560629: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-02-10 15:19:50.582805: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2699905000 Hz
Now we build the Critic model
Now we build the Critic model
Now we load the weight
Cannot find the weight
OMNeT++ Experiment Start.
Episode : 0 Replay Buffer 0
/home/shivam/keras/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:2325: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '

<!> Error: Could not load NED sources from 'omnet/router/': Declared package 'inet.examples.adhoc.hostautoconf' does not match expected package 'networksimulator.inet.examples.adhoc.hostautoconf' in file Scenario.ned
Traceback (most recent call last):
  File "ddpg.py", line 215, in <module>
    playGame(DDPG_config, train_indicator=1)
  File "ddpg.py", line 123, in playGame
    s_t1, r_t, done = env.step(a_t[0])
  File "/home/shivam/Documents/DRL/Environment.py", line 452, in step
    om_output = file_to_csv(self.folder + OMDELAY)
  File "/home/shivam/Documents/DRL/Environment.py", line 45, in file_to_csv
    with open(file_name, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'runs//t1612950590335656/Delay.txt'

**Comment by shivam46** [comment]
Can anyone help me with this issue ?
I dont know about this Delay.txt file error

**Comment by bill8363** [comment]
I also have the same problem but it's less like an Environment.py problem and more like an Omnet++ problem. I think I have to run Omnet++ before Delay.txt is generated but I don't know how to rule it out.
